# Site settings
title: Personal Dashboard
email: Ken@Volometrix.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl: "/projects/volometrix/gene" # the subpath of your site, e.g. /blog/
baseurl: "/design" # the subpath of your site, e.g. /blog/
# url: "http://ux.corp.volometrix.com" # the base hostname & protocol for your site
# url: "http://gyroscopestudios.com"
url: "https://volometrix.github.io"
twitter_username: gyrostu
github_username:  gyrostu

# Collections
collections:
  components:
    output: false

# Includes
collections:
  modules:
    output: true

# Build settings
markdown: kramdown